Don't add credHelper if there's no GCP credentials
As we know, gcloud auth configure-docker adds the Docker credHelper
entry to Docker's configuration file, or creates the file
if it doesn't exist.
But if there's no GCP credential file(defined by env
GOOGLE_APPLICATION_CREDENTIALS), which is often met in internal CI,
it would lead to a failure when doing
the normal docker operation:
"
ERROR: error getting credentials - err: exit status 1, out:
 `You do not currently have an active account selected.
See https://cloud.google.com/sdk/docs/authorizing for more information
"

So just ignore the credHelper adding operation if there's no
GCP credentials.

Signed-off-by: TrevorTaoARM <trevor.tao@arm.com>