[release-1.26] Deal with "replace-not-merge" in json-schema-validation new lib in Helm v3.18.5 (#57457) (#57516)
* Deal with "replace-not-merge" in json-schema-validation new lib in Helm v3.18.5 (#57457)

* Fix schema to allow _internal_defaults_do_not_set without breaking $ref

- Keeps a single source of truth for top-level keys in "$defs.values.properties".
- Helm uses santhosh-tekuri/jsonschema v6. For draft-07, when an object contains
$ref it seems siblings are ignored. https://github.com/santhosh-tekuri/jsonschema/blob/32784e992ee32ae73891b165b1319dd0bca87437/root.go#L101
- Having properties or additionalProperties at the root alongside $ref
means those siblings won’t be applied. With additionalProperties: false
in the referenced schema, unknown keys (like
_internal_defaults_do_not_set) are rejected.

Before:
```
helm lint .
==> Linting .
[ERROR] templates/: template: gateway/templates/service.yaml:1:22: executing "gateway/templates/service.yaml" at <.Values.service.type>: nil pointer evaluating interface {}.type

Error: 1 chart(s) linted, 1 chart(s) failed
```

After:
```
helm lint .
==> Linting .

1 chart(s) linted, 0 chart(s) failed
```

Related:

- https://github.com/istio/istio/pull/57426
- https://github.com/helm/helm/issues/31148
- https://github.com/istio/istio/issues/57354

Signed-off-by: Benoit Tigeot <benoit.tigeot@lifen.fr>

* Add 3 missing fields in schema

Avoid
```
--- FAIL: TestRender (0.00s)
    --- FAIL: TestRender/gateway-additional-containers (0.00s)
        helm_test.go:148:
            	Error Trace:	/home/prow/go/src/istio.io/istio/operator/pkg/helm/helm_test.go:148
            	Error:      	Received unexpected error:
            	            	render chart: converting values: values don't meet the specifications of the schema(s) in the following chart(s):
            	            	gateway:
            	            	- at '': additional properties 'additionalContainers' not allowed
            	Test:       	TestRender/gateway-additional-containers
    --- FAIL: TestRender/gateway-init-containers (0.00s)
        helm_test.go:148:
            	Error Trace:	/home/prow/go/src/istio.io/istio/operator/pkg/helm/helm_test.go:148
            	Error:      	Received unexpected error:
            	            	render chart: converting values: values don't meet the specifications of the schema(s) in the following chart(s):
            	            	gateway:
            	            	- at '': additional properties 'initContainers' not allowed
            	Test:       	TestRender/gateway-init-containers
    --- FAIL: TestRender/gateway-env-var-from (0.00s)
        helm_test.go:148:
            	Error Trace:	/home/prow/go/src/istio.io/istio/operator/pkg/helm/helm_test.go:148
            	Error:      	Received unexpected error:
            	            	render chart: converting values: values don't meet the specifications of the schema(s) in the following chart(s):
            	            	gateway:
            	            	- at '': additional properties 'envVarFrom' not allowed
            	Test:       	TestRender/gateway-env-var-from
```

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/57457/gencheck_istio/1959012558157385728
Signed-off-by: Benoit Tigeot <benoit.tigeot@lifen.fr>

* Add missing `make gen`

* Fix "Additional property pilot is not allowed"

When doing:

`go test -tags=integ -timeout 30s -run ^TestAmbientInstallMultiNamespace$ -v ./tests/integration/helm`

Signed-off-by: Benoit Tigeot <benoit.tigeot@lifen.fr>

* Fix "Additional property defaultRevision is not allowed"

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/57457/integ-helm_istio/1959744321842319360
Signed-off-by: Benoit Tigeot <benoit.tigeot@lifen.fr>

* Add missing release note

Signed-off-by: Benoit Tigeot <benoit.tigeot@lifen.fr>

* Fix english in releaseNotes

Signed-off-by: Benoit Tigeot <benoit.tigeot@lifen.fr>

---------

Signed-off-by: Benoit Tigeot <benoit.tigeot@lifen.fr>

* make gen

Signed-off-by: Keith Mattix II <keithmattix@microsoft.com>

---------

Signed-off-by: Benoit Tigeot <benoit.tigeot@lifen.fr>
Signed-off-by: Keith Mattix II <keithmattix@microsoft.com>
Co-authored-by: Benoit Tigeot <benoittgt@users.noreply.github.com>