Fix local test failures due to a wrong $KUBECONFIG (#8463)
Running `make test` locally fails if we have something in
our ~/.kube/config, as the tests will use that file by default:

```
...
--- FAIL: TestServices (30.00s)
	controller_test.go:59: Post https://192.168.99.100:8443/api/v1/namespaces: dial tcp 192.168.99.100:8443: i/o timeout
FAIL
FAIL	istio.io/istio/pilot/pkg/serviceregistry/kube	30.018s
...
```

Pointing the tests to use the same kubeconfig file as in use by
testEnvLocalK8S.sh fixes this issue, making local tests to pass.