Add 3 missing fields in schema
Avoid
```
--- FAIL: TestRender (0.00s)
    --- FAIL: TestRender/gateway-additional-containers (0.00s)
        helm_test.go:148:
            	Error Trace:	/home/prow/go/src/istio.io/istio/operator/pkg/helm/helm_test.go:148
            	Error:      	Received unexpected error:
            	            	render chart: converting values: values don't meet the specifications of the schema(s) in the following chart(s):
            	            	gateway:
            	            	- at '': additional properties 'additionalContainers' not allowed
            	Test:       	TestRender/gateway-additional-containers
    --- FAIL: TestRender/gateway-init-containers (0.00s)
        helm_test.go:148:
            	Error Trace:	/home/prow/go/src/istio.io/istio/operator/pkg/helm/helm_test.go:148
            	Error:      	Received unexpected error:
            	            	render chart: converting values: values don't meet the specifications of the schema(s) in the following chart(s):
            	            	gateway:
            	            	- at '': additional properties 'initContainers' not allowed
            	Test:       	TestRender/gateway-init-containers
    --- FAIL: TestRender/gateway-env-var-from (0.00s)
        helm_test.go:148:
            	Error Trace:	/home/prow/go/src/istio.io/istio/operator/pkg/helm/helm_test.go:148
            	Error:      	Received unexpected error:
            	            	render chart: converting values: values don't meet the specifications of the schema(s) in the following chart(s):
            	            	gateway:
            	            	- at '': additional properties 'envVarFrom' not allowed
            	Test:       	TestRender/gateway-env-var-from
```

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/57457/gencheck_istio/1959012558157385728
Signed-off-by: Benoit Tigeot <benoit.tigeot@lifen.fr>