Fix "release_istio_postsubmit" job failure - unknown flag
The "release_istio_postsubmit" job fails with the following error:
Error: unknown flag: --r2bucket
https://prow.istio.io/view/gs/istio-prow/logs/release_istio_postsubmit/2044520396853612544

This happens because "--r2bucket" flag has been recently added to the
"release-builder" flow -
istio/release-builder#2291.

But BUILDER_SHA within "prow/release-commit.sh" was not updated and
points for an older sha which is missing the required functionality.

Update the BUILDER_SHA with the sha contains the required flag.

Signed-off-by: Maxim Babushkin <mbabushk@redhat.com>