Update the BUILD rules for istio/api in the mixer repo.
NOTE: Trying to build the istio/api repo still fails as
several protos reference 'attribute.proto' instead of
'attributes.proto'.

```
$ bazel build @com_github_istio_api//:go_default_library
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_dougreid/5a64d675d9770ab00ead2cf89d1223e3/external/com_github_istio_api/BUILD:10:1: error executing shell command: 'cd external/com_github_istio_api && ../../bazel-out/host/bin/external/com_github_google_protobuf/protoc --descriptor_set_out=../../bazel-out/local-fastbuild/genfiles/external/com_github_istio_api/g...' failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
mixer/api/v1/attribute.proto: File not found.
mixer/api/v1/check.proto: Import "mixer/api/v1/attribute.proto" was not found or had errors.
mixer/api/v1/check.proto:28:3: "istio.mixer.v1.Attributes" seems to be defined in "mixer/api/v1/attributes.proto", which is not imported by "mixer/api/v1/check.proto".  To use it here, please add the necessary import.
Target @com_github_istio_api//:go_default_library failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.252s, Critical Path: 0.03s
```

Former-commit-id: 1a732a53e9bb447e9b409e3b5a758cf43424a84a