lint fixes
The following lint errors appear on master:
```
mixer/adapter/stackdriver/metric/bufferedClient.go:79:16:error:
monitoring.MetricProjectPath is deprecated: Use
fmt.Sprintf("projects/%s", project) instead.  (SA1019) (megacheck)
mixer/tools/adapterlinter/main.go:85:3:error: should replace loop with
rpts = append(rpts, doPackage(fs, pkg)...) (S1011) (megacheck)
```

- bufferedClient: seems cloud.google.com/go package is updated to
  0.18.0, which deprecates MetricProjectPath function.
- adapterlinter: seems a trivial warning of megacheck