lint / format fixes
The following lint errors are appearing on my environment for
some reasons -- possibly due to go 1.10rc2. Basically the fixes
themselves would be good to me.

Also I ran fmt.sh to clean up the code a bit.

Here are the error messages:

```
mixer/pkg/runtime2/runtime.go:54:2:error: field env is unused (U1000)
(megacheck)
mixer/pkg/runtime2/runtime.go:54:2:error: unused struct field
istio.io/istio/mixer/pkg/runtime2.Runtime.env (structcheck)
mixer/pkg/runtime2/runtime.go:178:17:error: error return value not
checked (cleanupHandlers(oldContext, oldHandlers, newHandlers,
maxCleanupDuration)) (errcheck)
mixer/pkg/server/args.go:32:11:error: struct of size 208 could be 200
(maligned)
mixer/test/client/check_report_disable/check_report_disable_test.go:25:7:error:
const checkOnlyFlags is unused (U1000) (megacheck)
mixer/test/client/check_report_disable/check_report_disable_test.go:29:7:error:
const reportOnlyFlags is unused (U1000) (megacheck)
mixer/test/client/check_report_disable/check_report_disable_test.go:29:7:error:
unused variable or constant reportOnlyFlags (varcheck)
mixer/test/client/check_report_disable/check_report_disable_test.go:25:7:error:
unused variable or constant checkOnlyFlags (varcheck)
pilot/pkg/proxy/envoy/v2/mesh.go:599:26:error: func
labelEndpoints.addLabelValue is unused (U1000) (megacheck)
pilot/pkg/proxy/envoy/v2/mesh.go:1012:32:error: func
DestinationRuleType.getUpdatedLabels is unused (U1000) (megacheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:72:2:error: unused variable or
constant allTestLabels (varcheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:34:2:error: unused variable or
constant testSubset2 (varcheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:482:6:error: func epListDebugInfo
is unused (U1000) (megacheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:30:2:error: const testLabelEnv is
unused (U1000) (megacheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:29:2:error: const testLabelVer is
unused (U1000) (megacheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:28:2:error: const testLabelApp is
unused (U1000) (megacheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:33:2:error: unused variable or
constant testSubset1 (varcheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:72:2:error: var allTestLabels is
unused (U1000) (megacheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:34:2:error: const testSubset2 is
unused (U1000) (megacheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:33:2:error: const testSubset1 is
unused (U1000) (megacheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:32:2:error: const testLabelShd is
unused (U1000) (megacheck)
pilot/pkg/proxy/envoy/v2/mesh_test.go:31:2:error: const testLabelExp is
unused (U1000) (megacheck)
security/cmd/istio_ca/main.go:66:17:error: struct of size 224 could be
216 (maligned)
security/cmd/node_agent_k8s/workload/main.go:67:18:error: error return
value not checked (defer conn.Close()) (errcheck)
security/pkg/probe/controller.go:172:3:error: should use for range
instead of for { select {} } (S1000) (megacheck)
```