Fix and Improve the building of Helloworld Image
Now the Dockerfile of Helloworld uses a wrong base image of
Python, it would lead to an error:

    SyntaxError: invalid syntax
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9z5clz/flask-json/
    You are using pip version 10.0.1, however version 20.3.4 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.

So we upgrade the base Python image to 3.4-onbuild, and add a
helloworld-v3 build to the helloworld.yaml in the
build_service.sh script.

Signed-off-by: trevor.tao <trevor.tao@arm.com>