Improvements to tag command (#32400)
* Improvements to tag command

* Allow external control plane to bypass in-cluster Istiod pod check
* Add check to ensure we don't have overlapping webhooks. For example:

```
$ grun ./istioctl/cmd/istioctl x revision tag generate istio-1611 --revision istio-1611
Error: creating tag would conflict:
Error [IST0139] (MutatingWebhookConfiguration istio-revision-tag-istio-1611 ) Webhook overlaps with others: [istio-sidecar-injector-istio-1611/sidecar-injector.istio.io]. This may cause injection to occur twice.
```

* confirm