kube-inject improvements: (#31955)
* When no pods available, fail instead of hanging forever. Example:
```
$ istioctl kube-inject -f ~/kube/apps/httpbin.yaml
Error: no pods matching selector "app=istiod,istio=pilot" found in namespace "istio-system"
```
* Allow --revision=default
* Make integration test respect revision flag

Co-authored-by: John Howard <howardjohn@google.com>